### ISSUE TITLE
Some "errors"

### ISSUE THREAD

**Issue by MalvinHiepp** [BytePhilHD/SpotifyLink#1]
I think we'll practice Java conventions again. You could revise your method names again. For example in the AuthorizationCodeExample.java in the authorization package in line 33 you can change the name of the method "authorizationCode_Sync" to "authorizationCodeSync". If we're in class right now (not related to conventions but fine) instead of using "else if" all the time, you could use a switch case statement. Looks nicer and is "less" code. Also, in this class (I haven't looked closely at the others) I see that you use the "System.out.println()" method. It's nothing bad, but as I've seen, you have your own console class that should take care of that for you. In addition, the messages in the console then look more uniform. I advise you to use Spring by the way. The framework runs more stable and better than Javalin. There are also better options, for example emails. But that is up to you. Looking around the Main, I advise you to create your own classes for methods like "copyFile" or "reader". If I were you, I would create an instance for the main so that you (if there are other variables) can set it to private. In order to use the conventions again, it would have been nice to structure your project as follows: de.bytephil.spotifylink" Then you name the Main SpotifyLink and then that fits again. Otherwise I only noticed small "errors". For example in the MessageType enum die formatting (everything on one line instead of one line for each bulleted list) Other than that, I really like the project and hope you continue it. Also, it would be nice to improve the named bugs. sorry for the long text, i'm a bit bored :)

**Comment by BytePhilHD** [comment]
Hi Schnoggy,
thanks for your detailed text about what I can improve. I am aware of most of your points, like naming classes and functions and using the sout instead of the Console Class, but I'm currently on vacation and programming a bit outside, so I haven't really cared about these points :). Of course, I will fix these problems when my backend is finished or when I'm back at home again, but for today, the code is a bit of a mess :)

Kind regards, Phil
